//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

use sea_orm::entity::prelude::*;
use serde::Serialize;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize)]
#[sea_orm(table_name = "user")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u64,
    #[sea_orm(unique)]
    pub username: String,
    pub is_admin: i8,
    pub level: u8,
    pub password: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::txt::Entity")]
    Txt,
}

impl Related<super::txt::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Txt.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
